name: Deploy with GH-Pages

on:
  # manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Tests pass
        run: yarn test

      - name: Build list
        run: yarn build
          
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages

    steps:   
      - name: Deploy list
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build
          
      - id: deployment
        uses: actions/deploy-pages@main

